Flownative:
  OpenIdConnect:
    Client:
      services: []
#        exampleService:
#          options:
#            discoveryUri: 'https://example.com/.well-known/openid-configuration'
#            clientId: '@!EDD5.370D.8247.FED9!0001!B1C9.92C1!1008!13DB.54D8.65DE.2761'
#            clientSecret: 'very-secret'

#Neos:
#  Flow:
#    http:
#      chain:
#        'postprocess':
#          chain:
#            'Flownative.OpenIdConnect.Client:setJwtCookie':
#              componentOptions:
#                # Use the same service name as below - the corresponding JWT will be stored in a cookie named "<serviceName>-jwt"
#                serviceName: 'exampleService'

#    security:
#      authentication:
#        providers:
#          'Flownative.OpenIdConnect.Client:OidcProvider':
#            label: 'OpenID Connect'
#            provider: 'Flownative\OpenIdConnect\Client\Authentication\OpenIdConnectProvider'
#            providerOptions:
#              roles: ['Acme.MyPackage:User']
#              accountIdentifierTokenValueName: 'inum'
#              serviceName: 'exampleService'
#            token: 'Flownative\OpenIdConnect\Client\Authentication\OpenIdConnectToken'
#            requestPatterns:
#              'Acme.MyPackage:Frontend':
#                pattern: 'Acme\MyPackage\Security\SiteRequestPattern'
#                patternOptions:
#                  'siteNodeName': 'mysite'
#                  'matchFrontend': true
#            entryPoint: 'Flownative\OpenIdConnect\Client\Authentication\OpenIdConnectEntryPoint'
#            entryPointOptions:
#              serviceName: 'acmeservice'
#              scope: 'inum user_name sap_custno'
