Neos:
  Flow:
    http:
      chain:
        'postprocess':
          chain:
            'Flownative.OpenIdConnect.Client:setJwtCookie':
              'position': 'after setSessionCookie'
              component: 'Flownative\OpenIdConnect\Client\Http\SetJwtCookieComponent'
              componentOptions:
                serviceName: 'flownative_oidc'
                secureCookie: true
                authenticationProviderName: 'Flownative.OpenIdConnect.Client:OidcProvider'
